### ISSUE TITLE
Cannot find type 'RealmApp' in scope

### ISSUE THREAD

**Issue by hongfeiyang** [capacitor-community/realm#1]
**Describe the bug**
App failed to build on Xcode 12.4, macOS 10.15

**To Reproduce**
Follow the instructions in read me. Create a new ionic app, import realm plugin, without doing anything just build an iOS version of the app, Xcode will fail to build with multiple errors that seems to be related to cannot find 'RealmApp' 'AppCredentials' in scope.

**Expected behavior**
Should be able to build at least

**Screenshots**
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/19302128/107845312-a8887c00-6e2e-11eb-98b7-e7d284c5332b.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.4

**Additional context**
